import { supabase } from '@/integrations/supabase/client';

const loadImageAsBase64 = async (url: string): Promise<string> => {
  const res = await fetch(url);
  const blob = await res.blob();
  return new Promise((resolve) => {
    const reader = new FileReader();
    reader.onloadend = () => resolve(reader.result as string);
    reader.readAsDataURL(blob);
  });
};

export const generateEvidencePDF = async (
  scan: any,
  photos: any[],
  confirmation: any,
  comparison: any | null,
  findings: any[]
) => {
  const { default: jsPDF } = await import('jspdf');
  const doc = new jsPDF('p', 'mm', 'a4');
  const W = 210;

  // Page 1: Cover
  doc.setFontSize(20);
  doc.setFont('helvetica', 'bold');
  doc.text('VEHICLE CONDITION', W / 2, 40, { align: 'center' });
  doc.text('EVIDENCE REPORT', W / 2, 50, { align: 'center' });

  doc.setFontSize(11);
  doc.setFont('helvetica', 'normal');
  doc.text('Generated by CarShake — carshake.online', W / 2, 62, { align: 'center' });

  let y = 80;
  const info = [
    ['Date', new Date().toLocaleString()],
    ['Scan ID', scan.id],
    ['Location', scan.address || `${scan.gps_lat?.toFixed(4)}, ${scan.gps_lon?.toFixed(4)}` || 'N/A'],
    ['Type', scan.type === 'dropoff' ? 'Drop-off' : 'Pickup'],
    ['Confirmation', confirmation ? `Confirmed at ${new Date(confirmation.confirmed_at).toLocaleString()} via ${confirmation.method}` : 'Unconfirmed'],
  ];

  info.forEach(([label, value]) => {
    doc.setFont('helvetica', 'bold');
    doc.text(label + ':', 20, y);
    doc.setFont('helvetica', 'normal');
    doc.text(String(value), 60, y);
    y += 8;
  });

  if (scan.hash_sha256) {
    doc.setFont('helvetica', 'bold');
    doc.text('SHA-256:', 20, y);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.text(scan.hash_sha256, 60, y);
    doc.setFontSize(11);
  }

  // Page 2: Photos
  if (photos.length > 0) {
    doc.addPage();
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text(scan.type === 'dropoff' ? 'DROP-OFF RECORD' : 'PICKUP RECORD', W / 2, 20, { align: 'center' });

    const cols = 4;
    const imgW = 42;
    const imgH = 32;
    const startX = 13;
    const startY = 30;
    const gapX = 4;
    const gapY = 12;

    for (let i = 0; i < photos.length; i++) {
      const col = i % cols;
      const row = Math.floor(i / cols);
      const x = startX + col * (imgW + gapX);
      const yPos = startY + row * (imgH + gapY);

      try {
        const url = supabase.storage.from('scan-photos').getPublicUrl(photos[i].storage_path).data.publicUrl;
        const base64 = await loadImageAsBase64(url);
        doc.addImage(base64, 'JPEG', x, yPos, imgW, imgH);
        doc.setFontSize(7);
        doc.setFont('helvetica', 'normal');
        doc.text(photos[i].angle_name, x, yPos + imgH + 3);
      } catch {
        doc.setFontSize(8);
        doc.text(`[Photo ${i + 1} unavailable]`, x, yPos + imgH / 2);
      }
    }

    // Metadata below photos
    const metaY = startY + Math.ceil(photos.length / cols) * (imgH + gapY) + 8;
    doc.setFontSize(9);
    doc.setFont('helvetica', 'normal');
    if (scan.gps_lat) doc.text(`GPS: ${scan.gps_lat.toFixed(6)}, ${scan.gps_lon.toFixed(6)}`, 20, metaY);
    doc.text(`Timestamp: ${new Date(scan.created_at).toISOString()}`, 20, metaY + 5);
  }

  // Page 3: Comparison
  if (comparison) {
    doc.addPage();
    doc.setFontSize(16);
    doc.setFont('helvetica', 'bold');
    doc.text('AI CONDITION COMPARISON', W / 2, 20, { align: 'center' });

    let cy = 35;
    if (comparison.status === 'no_changes') {
      doc.setFontSize(14);
      doc.text('NO CHANGES DETECTED', W / 2, cy, { align: 'center' });
      cy += 10;
      doc.setFontSize(10);
      doc.setFont('helvetica', 'normal');
      doc.text('All angles verified. Vehicle condition unchanged.', W / 2, cy, { align: 'center' });
    } else {
      doc.setFontSize(14);
      doc.text(`${comparison.total_differences} DIFFERENCES FOUND`, W / 2, cy, { align: 'center' });
      cy += 12;

      findings.forEach((f: any) => {
        if (cy > 270) { doc.addPage(); cy = 20; }
        doc.setFontSize(10);
        doc.setFont('helvetica', 'bold');
        doc.text(`• ${f.location} [${f.severity?.toUpperCase()}]`, 20, cy);
        cy += 5;
        doc.setFont('helvetica', 'normal');
        doc.text(f.description, 25, cy, { maxWidth: 160 });
        cy += 8;
      });
    }

    cy += 10;
    doc.setFontSize(8);
    doc.setFont('helvetica', 'italic');
    doc.text('Analysis performed by AI. Results are advisory and should be verified by qualified professionals.', 20, cy, { maxWidth: 170 });
  }

  // Footer on last page
  const pageCount = doc.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(7);
    doc.setFont('helvetica', 'normal');
    doc.text(`CarShake Evidence Report · Scan ID: ${scan.id} · Page ${i} of ${pageCount}`, W / 2, 290, { align: 'center' });
  }

  doc.save(`carshake-evidence-${scan.id.slice(0, 8)}.pdf`);
};
