#!/usr/bin/env python3
"""
CarShake cost-of pSEO generator.
Produces /cost-of/{damage-type}/index.html for ~15 common damage types.

Mirrors the exact HTML shell, JSON-LD blocks (Article + BreadcrumbList +
FAQPage), cs-page body, and BRUNSON TRUST BAR CTA of the hand-built
/cost-of/valet-damage-repair page. Cost figures are grounded in the ranges
already published on the site, extended conservatively. No invented stats.

Usage: python3 _gen_cost_of.py [--hub]
"""
import re, json
from pathlib import Path

ROOT = Path("/Users/sipi/carshake")
BASE = "https://carshake.online"
TODAY = "2026-07-26"
PUBDATE = "2026-07-26"

DAMAGE_TYPES = [
    {"slug":"door-ding","category":"Exterior body","h1":"How Much Does a Door Ding Cost to Fix?","meta_desc":"Door ding repair costs $100 to $500+ depending on whether the paint is intact. Paintless dent repair vs body shop, insurance deductibles, and how to prove a valet or parking-lot ding.","lede":"A door ding costs anywhere from $100 to $500+ to fix. The number you actually pay depends on one thing: whether the paint is cracked. Paintless dent repair can erase a clean ding in under an hour; a cracked-paint ding becomes a body-shop job.","cards":[("Small ding, paint intact (PDR)","$100\u2013$250","Paintless dent repair uses specialized tools to massage the metal back into shape from behind the panel. No sanding, no painting, done in an hour or two."),("Larger ding, paint intact (PDR)","$150\u2013$350","Bigger dents (golf-ball size and up) take longer and may require glue-pulling, but still avoid the paint shop if the finish is unbroken."),("Ding with cracked or chipped paint","$300\u2013$600","Once the paint is broken, it becomes a body-shop job: filler, primer, base coat, clear coat, and blending into the surrounding panel."),("Deep crease dent with paint damage","$500\u2013$1,000","Sharp creases stretch the metal and often crack the paint. Expect filler, multiple paint stages, and a full day at the shop.")],"insurance_q":"Will my insurance cover a door ding?","insurance_a":"It depends on the cause. If another driver dinged your parked car and left, that is usually a collision claim subject to your deductible ($500\u2013$1,000), and a $200 dent is cheaper to fix yourself than to file. If the ding happened in a valet's or shop's custody, their garagekeeper's or general liability policy should cover it, but only if you can prove it occurred on their watch.","valet_q":"How do I prove a valet caused the door ding?","valet_a":"With a timestamped before-and-after photo record of your car at handover. Without a pre-handover scan showing the door was clean, the valet will claim the ding was already there, and you have no recourse. A 60-second scan before you hand over the keys is the single highest-leverage thing you can do.","related":[("Cost of Valet Damage Repair","/cost-of/valet-damage-repair"),("Valet Damage Disputes Guide","/learn/valet-damage-disputes"),("Free Claim Letter Generator","/free/valet-damage-claim-letter")]},
    {"slug":"curb-rash","category":"Wheels & tires","h1":"Curb Rash Repair Cost: What You'll Actually Pay","meta_desc":"Curb rash repair costs $75 to $200 per wheel for a professional refinish, or $400+ for machined or chrome rims. DIY kits, when to refinish vs replace, and how to prove a valet curbed your wheel.","lede":"Curb rash \u2014 the scuffed, gouged alloy where a wheel met a curb \u2014 costs $75 to $200 per wheel to refinish professionally. Machined or chrome finishes cost more, and a cracked wheel means replacement, not repair.","cards":[("Light cosmetic scuff (DIY kit)","$20\u2013$50","A DIY curb-rash kit with sandpaper, filler, and rattle-can paint can hide light scuffs on a painted alloy wheel. Good enough for a daily driver, not for a show car."),("Professional alloy refinish","$75\u2013$150","A wheel shop sands out the gouge, fills, repaints, and clear-coats the wheel off the car. Turnaround is usually 1\u20132 days per wheel."),("Machined-finish wheel repair","$150\u2013$300","Machined (diamond-cut) faces require a CNC lathe to restore, and only some shops have one. Over-machining thins the metal, so a wheel can only be re-cut a few times."),("Chrome wheel refinish","$200\u2013$400+","Chrome must be stripped and re-plated \u2014 a multi-step chemical process few shops do in-house. Badly pitted chrome often means replacement."),("Cracked or bent wheel (replace)","$400\u2013$900","A curb hit hard enough to crack or bend the rim is not a refinish job. A replacement OEM alloy typically runs $400\u2013$900; forged or OEM-plus wheels cost more.")],"insurance_q":"Does insurance cover curb rash?","insurance_a":"Generally no, unless the damage is part of a larger covered incident (like a collision). Routine curb rash from parking is considered wear and tear, and most comprehensive policies exclude it. If a valet curbed your wheel during a handover, their liability is the better route \u2014 but again, only with proof it happened in their custody.","valet_q":"The valet curbed my wheel \u2014 what now?","valet_a":"Photograph the wheel before you leave the lot, then report it to the supervisor immediately while you are still on the property. A timestamped pre-handover photo of the clean wheel is what turns a denial (\u201cit was already like that\u201d) into a paid claim. Scanning the wheels as part of your pre-handover walk-around is the move.","related":[("Cost of Valet Damage Repair","/cost-of/valet-damage-repair"),("Understanding Car Damage Types","/learn/understanding-car-damage-types"),("Vehicle Handover Best Practices","/learn/vehicle-handover-best-practices")]},
    {"slug":"bumper-scrape","category":"Exterior body","h1":"Bumper Scrape Repair Cost: The Real Numbers","meta_desc":"A scraped bumper costs $150 to $2,000+ to fix. Light scuff buffing vs repainting vs replacement, sensor recalibration, and how to prove a valet scraped your bumper.","lede":"A bumper scrape runs from $150 for a buffable scuff to $2,000+ for a full repaint or replacement. The biggest cost driver is not the scrape itself \u2014 it is the parking sensors, cameras, and radar hidden behind modern bumpers.","cards":[("Light clear-coat scuff (buff)","$100\u2013$250","If the scrape only went through the clear coat, a detailer can wet-sand and buff it out in under an hour. No paint matching needed."),("Paint transfer, no clear-coat break","$150\u2013$350","Another car's paint rubbed off onto your bumper. Compounding and polishing removes the transfer; a light clear-coat touch-up seals it."),("Deep scrape through the paint","$400\u2013$800","Sanding, primer, base coat, clear coat, and blending. Most body shops charge a panel minimum of $300\u2013$500 regardless of scrape size."),("Full bumper repaint","$600\u2013$1,200","When the scrape spans most of the bumper or the existing paint is aged, a full repaint (remove, strip, paint, reinstall) looks better than a patch."),("Bumper cover replacement + sensors","$900\u2013$2,000+","A torn cover needs replacement. Add sensor recalibration if the scrape cracked a parking-sensor or radar housing \u2014 calibration alone can run $150\u2013$400.")],"insurance_q":"Is a bumper scrape worth an insurance claim?","insurance_a":"Usually not, unless the repair exceeds your deductible. A $400 scrape on a $500 deductible means you pay the whole bill and a claim may raise your premium. The exception is when the scrape happened in a valet's or shop's custody \u2014 then their liability policy should pay, and your evidence (not your deductible) is what wins it.","valet_q":"How do I prove the valet scraped my bumper?","valet_a":"A pre-handover photo of the bumper, timestamped and geotagged, then a post-handover photo of the fresh scrape. The valet will otherwise claim pre-existing damage. Scanning the front and rear bumpers \u2014 the two highest-risk zones \u2014 before you hand over the keys is exactly what catches this.","related":[("Cost of Valet Damage Repair","/cost-of/valet-damage-repair"),("How to Dispute Valet Damage","/learn/how-to-dispute-valet-damage"),("Insurance Claim Photo Tips","/learn/insurance-claim-photo-tips")]},
    {"slug":"paint-scratch","category":"Exterior body","h1":"Car Paint Scratch Repair Cost: A Full Breakdown","meta_desc":"Car paint scratch repair costs $20 for a DIY touch-up to $1,500+ for a full panel respray. Clear-coat vs base-coat vs deep scratches, and how to prove a valet or parking scratch.","lede":"A car scratch costs anywhere from $20 for a home touch-up pen to $1,500+ for a full panel respray. The price hinges on how deep the scratch is \u2014 clear coat, base coat, or primer \u2014 because each layer down means more labor and material.","cards":[("Clear-coat scratch (buff)","$75\u2013$200","A scratch that hasn't broken through to the color coat can often be wet-sanded and buffed out by a detailer. Fingernail test: if your nail barely catches, it's clear-coat depth."),("Base-coat scratch (touch-up)","$100\u2013$300","Through the clear coat into the color. A pro touch-up with matched paint and a clear-coat blend hides it well from a few feet away."),("Deep scratch to primer/metal","$300\u2013$800","Through the color into the primer or bare metal. Requires sanding, primer, base coat, clear coat, and blending into the adjacent panel so the new paint doesn't stand out."),("Keyed scratch (long, deep)","$500\u2013$1,500+","A key dragged across a door or quarter panel is usually deep and long, often crossing body lines. Full panel prep and respray, sometimes two panels to blend."),("Multiple-panel scratch","$1,000\u2013$2,500+","When a scratch runs across two or more panels (e.g., door + quarter), each panel is billed separately and the blending work multiplies.")],"insurance_q":"Should I claim a paint scratch on insurance?","insurance_a":"Only if the repair clearly exceeds your deductible and you can identify a responsible party. A $300 scratch on a $500 deductible is an out-of-pocket fix. Comprehensive coverage applies for vandalism (a keyed car), but you'll still pay the deductible and a claim can raise rates. For a scratch in a valet's or shop's custody, pursue their liability first with timestamped proof.","valet_q":"How do I prove a valet scratched my car?","valet_a":"Photograph every panel before handover with a timestamped, geotagged scan, then again at pickup. The before-scan is what defeats the standard \u201cpre-existing damage\u201d defense. Park scratches and valet scratches look identical at the end \u2014 only a pre-handover record separates the two.","related":[("Cost of Valet Damage Repair","/cost-of/valet-damage-repair"),("How to Document Car Damage","/learn/how-to-document-car-damage"),("Understanding Car Damage Types","/learn/understanding-car-damage-types")]},
    {"slug":"keyed-car","category":"Exterior body","h1":"Keyed Car Repair Cost: What Vandalism Costs to Fix","meta_desc":"A keyed car costs $500 to $2,500+ to repair depending on length and depth. Comprehensive insurance, police reports, and how to document vandalism for a claim.","lede":"A keyed car costs $500 to $2,500+ to fix because the scratch is long, deep, and often crosses body lines and panels. It is the most expensive common scratch repair, and it is usually covered by comprehensive insurance \u2014 if you have the documentation.","cards":[("Short keyed scratch (one panel)","$500\u2013$900","Sanding, primer, base, clear, and blend on a single panel. Even a \u201cshort\u201d key mark is usually deeper than a parking scratch."),("Full side keyed (door + quarter)","$1,000\u2013$1,800","Key marks typically run the length of a door and into the quarter panel. Two panels means two prep-and-paint cycles plus blending."),("Keyed across multiple body lines","$1,500\u2013$2,500+","When the scratch crosses the hood, roof, or multiple doors, each panel is a separate paint job and the color-matching across panels must be seamless."),("Full vehicle respray (severe)","$3,000\u2013$6,000+","Whole-car vandalism sometimes justifies a complete respray. Insurance may total an older low-value car before approving this.")],"insurance_q":"Does comprehensive insurance cover a keyed car?","insurance_a":"Yes \u2014 keyed damage is vandalism, and comprehensive coverage pays for it subject to your deductible. File a police report first (most insurers require it for vandalism claims), photograph every scratch, and submit the report with your claim. Without comprehensive coverage on the policy, you pay out of pocket.","valet_q":"What if my car was keyed while in a valet or lot's custody?","valet_a":"The lot operator's or valet company's general liability or garagekeeper's policy is the primary target, but they will argue the vandalism was outside their control. Your strongest leverage is a timestamped condition record at handover and a second scan at pickup showing the damage appeared in between, plus the lot's own surveillance footage (request it in writing immediately before it's overwritten).","related":[("Cost of Valet Damage Repair","/cost-of/valet-damage-repair"),("Insurance Claim Photo Tips","/learn/insurance-claim-photo-tips"),("How to File a Valet Damage Claim","/learn/valet-damage-insurance-claims")]},
    {"slug":"hail-damage","category":"Exterior body","h1":"Hail Damage Repair Cost: PDR vs Conventional","meta_desc":"Hail damage repair costs $75 per dent for light PDR to $10,000+ for severe storms. Paintless dent repair vs body work, insurance claims, and documenting hail damage.","lede":"Hail damage ranges from $75 per dent for paintless dent repair (PDR) to $10,000+ for a severe storm that totals a car. PDR is the go-to because hail dents rarely break the paint \u2014 and it's almost always a comprehensive insurance claim.","cards":[("Light hail (few dents, PDR)","$75\u2013$150 per dent","A handful of small dents on flat panels. PDR techs work the dents out from behind using rods and glue-pulling. No paint, no fillers."),("Moderate hail (full hood/roof)","$2,500\u2013$5,000","Dozens of dents across the hood, roof, and trunk. PDR is still viable if the paint is intact; total labor time goes up sharply."),("Severe hail (every panel)","$5,000\u2013$10,000+","Large dents across every horizontal surface. Some panels may need conventional body work or replacement if the metal is stretched too thin for PDR."),("Storm that cracks paint","$7,000\u2013$15,000+","Once hail chips the paint, each dent becomes a body-shop repair. Severe cases often total older or lower-value vehicles.")],"insurance_q":"Is hail damage worth an insurance claim?","insurance_a":"Almost always yes \u2014 hail is a comprehensive peril and the repairs frequently exceed the deductible. Comprehensive claims for acts of nature typically do not raise premiums the way at-fault collision claims do. Document every dent with photos immediately after the storm, before any rental or lot can argue the dents pre-existed.","valet_q":"My car got hailed on while parked \u2014 who pays?","valet_a":"Your own comprehensive coverage is the reliable path; a lot or valet will usually not accept liability for weather. The risk is being blamed for pre-existing dents at your next rental return or trade-in \u2014 a timestamped scan after the hailstorm establishes that the dents existed on a specific date and weren't caused later by you.","related":[("Cost of Valet Damage Repair","/cost-of/valet-damage-repair"),("Insurance Claim Photo Tips","/learn/insurance-claim-photo-tips"),("Diminished Value Claims","/learn/diminished-value")]},
    {"slug":"windshield-chip","category":"Glass & lights","h1":"Windshield Chip and Crack Repair Cost","meta_desc":"A windshield chip costs $50 to $150 to fill, or $200 to $1,000+ to replace. When to repair vs replace, insurance coverage, and ADAS recalibration costs.","lede":"A windshield chip costs $50 to $150 to fill with resin if it's smaller than a quarter and not in the driver's line of sight. A crack, or a chip that's spread, means full replacement \u2014 $200 to $1,000+, more if your car has a head-up display or ADAS cameras.","cards":[("Small chip fill (resin)","$50\u2013$150","A technician injects resin into a chip smaller than a quarter, cures it with UV, and polishes it flat. Takes 30\u201345 minutes and often free with glass coverage."),("Short crack repair (under 6 inches)","$100\u2013$200","Longer cracks can sometimes be filled if caught early, but anything over ~6 inches or in the driver's view usually requires replacement."),("Standard windshield replacement","$200\u2013$500","A typical sedan or SUV windshield with no special features. Aftermarket glass is cheaper; OEM costs more."),("Windshield w/ HUD or sensors","$500\u2013$1,000+","Head-up displays, rain sensors, acoustic glass, and lane-keeping cameras add cost \u2014 and the cameras must be recalibrated after replacement."),("ADAS recalibration","$150\u2013$400 extra","If your windshield has a forward-facing camera, recalibration is mandatory after replacement or your safety systems won't work correctly.")],"insurance_q":"Is windshield damage covered by insurance?","insurance_a":"Comprehensive coverage pays for windshield damage, and many states (and many policies) offer zero-deductible glass coverage specifically for this. Check your policy \u2014 if you have full glass coverage, the repair or replacement is often free. Otherwise it's subject to your comprehensive deductible.","valet_q":"What if the windshield crack happened while the valet had my car?","valet_a":"Windshield damage is harder to attribute to a valet than body damage because it can come from road debris during a short drive. A pre-handover scan of the glass (front and rear) establishes the windshield was intact when you handed over the keys, which is what you need to push back if a new crack appears at pickup.","related":[("Cost of Valet Damage Repair","/cost-of/valet-damage-repair"),("Insurance Claim Photo Tips","/learn/insurance-claim-photo-tips"),("Vehicle Handover Best Practices","/learn/vehicle-handover-best-practices")]},
    {"slug":"cracked-tail-light","category":"Glass & lights","h1":"Cracked Tail Light Repair Cost: What You'll Pay","meta_desc":"A cracked tail light costs $50 for a DIY cover to $600+ for a full LED assembly replacement. Repair vs replace, when lens tape is enough, and proving parking damage.","lede":"A cracked tail light costs $50 for a DIY lens repair up to $600+ to replace a modern LED assembly. The cost swings wildly because a traditional bulb housing is cheap, while an integrated LED panel can cost hundreds just for the part.","cards":[("Lens crack seal (DIY tape/kits)","$10\u2013$30","Red lens tape or a UV-cure repair kit keeps water out and passes a roadside inspection temporarily. Not a permanent fix."),("Aftermarket lens cover replacement","$50\u2013$150","For older cars with separate, replaceable lens covers (not sealed LED units). Bolt-on, no programming."),("OEM tail light assembly (bulb type)","$100\u2013$350","A full sealed-assembly replacement for a conventional bulb housing. Part plus 30\u201360 minutes of labor."),("LED / integrated tail light assembly","$300\u2013$900","Modern LED panels are single sealed units \u2014 you replace the whole assembly, not a bulb. Luxury and EV tail lights run higher."),("Tail light + body/paint repair","$400\u2013$1,000+","A hard impact that cracked the light often also damaged the surrounding quarter panel. Add body work and paint to the assembly cost.")],"insurance_q":"Will insurance pay for a cracked tail light?","insurance_a":"Only if it's part of a larger covered incident (a collision or a hit while parked). A lone cracked tail light is usually under the deductible. If it happened in a valet's or lot's custody, their liability is the route \u2014 but you need to prove the light was intact at handover.","valet_q":"How do I prove a valet cracked my tail light?","valet_a":"Include all lights (front and rear) in your pre-handover scan. A timestamped photo of an intact tail light, then a photo of the cracked one at pickup, is the evidence that defeats a \u201cpre-existing damage\u201d claim. Tail lights are easy to overlook because drivers rarely photograph them \u2014 which is exactly why they're a common valet dispute.","related":[("Cost of Valet Damage Repair","/cost-of/valet-damage-repair"),("How to Document Car Damage","/learn/how-to-document-car-damage"),("Understanding Car Damage Types","/learn/understanding-car-damage-types")]},
    {"slug":"side-mirror","category":"Glass & lights","h1":"Broken Side Mirror Repair Cost: The Full Picture","meta_desc":"A broken side mirror costs $40 for a slip-on glass to $1,500+ for a power-folding, heated, camera-equipped assembly. Repair vs replace, and proving a tight-spot break.","lede":"A broken side mirror runs $40 for a stick-on replacement glass to $1,500+ for a power-folding, heated, blind-spot-camera assembly. Like tail lights, the cost is all about the tech packed into the part.","cards":[("Replacement mirror glass only","$40\u2013$120","If the housing is intact and only the glass is cracked, a stick-on or clip-in replacement glass is cheap and DIY-able in 10 minutes."),("Manual mirror assembly","$80\u2013$250","A basic manual-adjust mirror housing and glass. Bolt-on replacement, no wiring complexity."),("Power mirror assembly","$150\u2013$500","Power-adjustable mirror with heating. Part cost rises with motor and heating elements; labor includes door-panel removal and wiring."),("Power-folding / blind-spot mirror","$400\u2013$1,200","Folding motors, turn-signal repeaters, and blind-spot warning lights add electronics. Luxury vehicles run to the top of the range."),("Mirror w/ side camera (ADAS)","$800\u2013$1,500+","Mirrors with integrated cameras (e.g., for 360\u00b0 view or lane-change assist) require recalibration after replacement, adding $150\u2013$400.")],"insurance_q":"Does insurance cover a broken side mirror?","insurance_a":"It depends on the cause. A mirror clipped in a tight parking garage or by a passing car is a collision claim subject to your deductible \u2014 often not worth filing for a $200 manual mirror. If it happened in a valet's custody, their liability is the better target, provided you can prove the mirror was intact at handover.","valet_q":"How do I prove a valet broke my side mirror?","valet_a":"Side mirrors are one of the most common valet damage items because of tight garage lanes. A pre-handover scan that captures both mirrors (folded and extended), then a post-pickup scan of the broken mirror, is the proof. Mirrors fold and unfold in transit, so photographing them in their parked position at handover establishes the baseline.","related":[("Cost of Valet Damage Repair","/cost-of/valet-damage-repair"),("How to Dispute Valet Damage","/learn/how-to-dispute-valet-damage"),("Vehicle Handover Best Practices","/learn/vehicle-handover-best-practices")]},
    {"slug":"wheel-damage","category":"Wheels & tires","h1":"Wheel Damage Repair Cost: Potholes, Curbs, and Bends","meta_desc":"Wheel damage costs $75 to refinish a scuffed alloy, $100\u2013$200 to fix a bent rim, or $400\u2013$900+ to replace a cracked wheel. Pothole claims, road-hazard coverage, and proof.","lede":"Wheel damage runs $75 to refinish a curb scuff, $100\u2013$200 to straighten a bent rim, and $400\u2013$900+ to replace a cracked wheel. The damage type dictates everything \u2014 cosmetic, structural, or a road-hazard blowout.","cards":[("Alloy refinish (curb scuff)","$75\u2013$200","Sanding, filling, repainting, and clear-coating a scuffed alloy. See our curb-rash guide for the full breakdown."),("Bent rim straightening","$100\u2013$200","A pothole bend that causes a vibration can often be hydraulically straightened by a wheel specialist. Not all bends are repairable."),("Cracked wheel repair (weld)","$125\u2013$250","Some hairline cracks can be TIG-welded, though welding a load-bearing wheel is debated. Many shops will not weld a barrel crack."),("Replacement alloy wheel (OEM)","$400\u2013$900","A new OEM alloy for a mainstream car. Forged, OEM-plus, or large-diameter wheels cost more."),("Luxury / forged wheel replacement","$800\u2013$2,500+","Forged and OEM-plus wheels on performance and luxury vehicles can each cost thousands to replace.")],"insurance_q":"Does insurance cover pothole wheel damage?","insurance_a":"Pothole damage is typically a collision claim under your own policy, subject to your deductible. A single bent rim often costs less than the deductible, but a destroyed tire-plus-wheel-plus-suspension hit can exceed it. Road-hazard coverage on your tire/wheel warranty or a separate wheel-and-tire plan is the cleaner route for cosmetic damage.","valet_q":"Can I prove a valet damaged my wheel?","valet_a":"Wheels are easy to attribute to a valet if you have a pre-handover photo of each one \u2014 curb rash, bends, and cracks are all visible from a few feet away. A timestamped scan of all four wheels at handover, then again at pickup, is the record that turns \u201calready like that\u201d into a paid repair.","related":[("Curb Rash Repair Cost","/cost-of/curb-rash"),("Cost of Valet Damage Repair","/cost-of/valet-damage-repair"),("Vehicle Handover Best Practices","/learn/vehicle-handover-best-practices")]},
    {"slug":"dent-without-paint","category":"Exterior body","h1":"Dent Repair Cost When the Paint Is Intact (PDR)","meta_desc":"A dent with intact paint costs $100\u2013$350 for paintless dent repair. PDR vs body shop, size and location factors, and how to prove a parking or valet dent.","lede":"A dent where the paint is unbroken is the best-case scenario: paintless dent repair (PDR) can often restore the panel for $100\u2013$350 without sanding, fillers, or repainting. Once the paint cracks, costs jump sharply.","cards":[("Small dent, paint intact (PDR)","$100\u2013$250","A golf-ball-sized dent on a flat panel. A PDR tech works the metal back from behind using specialized rods. Usually done in under an hour."),("Large dent, paint intact (PDR)","$150\u2013$350","Bigger dents take longer and may need glue-pulling, but PDR still avoids the paint shop as long as the finish is unbroken."),("Dent on a body line / crease","$200\u2013$400","Dents across sharp body creases are harder to massage out cleanly and take more skill (and time) to resolve via PDR."),("Multiple dents (hail-style)","$75\u2013$150 per dent","Volume pricing for many small dents (common with hail). See our hail-damage guide for storm-scale pricing."),("Dent where PDR isn't possible","$400\u2013$900","If the dent is on an edge, double-panel, or a plastic bumper, PDR may not be an option and it becomes a conventional body-shop repair.")],"insurance_q":"Is a dent worth an insurance claim?","insurance_a":"Usually not for a single dent under your deductible. A $200 PDR repair on a $500 deductible is an out-of-pocket job. The exception is a dent caused in a valet's or shop's custody \u2014 then their liability should cover it, and your proof (a pre-handover scan showing the clean panel) is what wins the claim.","valet_q":"How do I prove a valet caused the dent?","valet_a":"A pre-handover scan of every exterior panel, timestamped and geotagged, then a post-pickup scan showing the new dent. Without the before-record, the valet will claim pre-existing damage \u2014 which is often impossible to disprove after the fact. Sixty seconds of scanning before you hand over the keys is the entire game.","related":[("Cost of Valet Damage Repair","/cost-of/valet-damage-repair"),("Door Ding Repair Cost","/cost-of/door-ding"),("How to Document Car Damage","/learn/how-to-document-car-damage")]},
    {"slug":"headlight-haze","category":"Glass & lights","h1":"Headlight Restoration and Replacement Cost","meta_desc":"Hazy headlight restoration costs $50\u2013$150 to refinish, or $200\u2013$2,000+ to replace a modern LED or matrix assembly. DIY kits, safety inspection, and UV protection.","lede":"Restoring a hazy, yellowed headlight costs $50\u2013$150 professionally; replacing a modern LED or matrix headlight assembly runs $200 to $2,000+. Haze is a wear item you can fix; a cracked or failed unit is a part replacement.","cards":[("DIY restoration kit","$15\u2013$40","Sanding discs, polishing compound, and a UV clear coat. Works well for mild haze; results depend heavily on technique and on sealing the lens afterward."),("Professional restoration","$50\u2013$150 per pair","A detailer sands through the grits, polishes, and applies a durable UV-clear. Lasts 1\u20133 years depending on the topcoat quality."),("Halogen assembly replacement","$100\u2013$300","A conventional halogen headlight for an older or mainstream car. Part plus labor; no programming."),("LED / HID assembly replacement","$300\u2013$1,000","Modern LED or projector-HID units are sealed assemblies \u2014 you replace the whole unit, not a bulb. Part cost dominates."),("Matrix / adaptive LED assembly","$1,000\u2013$2,500+","Adaptive driving-beam and matrix LED units (luxury and newer EVs) each cost thousands and often require software recalibration after install.")],"insurance_q":"Is headlight damage covered by insurance?","insurance_a":"A cracked or smashed headlight from a collision or road debris is a comprehensive or collision claim, subject to your deductible. Pure haze and yellowing is wear and tear and is not covered \u2014 that is a maintenance cost. If a headlight was cracked during a handover, a pre-handover scan of the lights is what attributes it.","valet_q":"How do I prove headlight damage happened at handover?","valet_a":"Include the front lights in your pre-handover scan (they're easy to skip because they're at knee height). A timestamped photo of an intact headlight at drop-off, then a photo of the cracked lens at pickup, is the record that defeats a pre-existing-damage claim.","related":[("Cost of Valet Damage Repair","/cost-of/valet-damage-repair"),("Insurance Claim Photo Tips","/learn/insurance-claim-photo-tips"),("Understanding Car Damage Types","/learn/understanding-car-damage-types")]},
    {"slug":"torn-seat-interior","category":"Interior","h1":"Torn or Damaged Car Seat Repair Cost","meta_desc":"A torn car seat costs $100 for a vinyl patch to $1,500+ for a full leather reupholster. Leather vs cloth vs performance suede, and how to prove a rideshare or valet tear.","lede":"A torn car seat runs $100 for a vinyl patch kit up to $1,500+ for a full leather reupholster. Interior damage is one of the hardest things to attribute after the fact \u2014 which is exactly why a pre-handover scan of the cabin matters for rentals and rideshare.","cards":[("Vinyl / cloth patch (DIY)","$20\u2013$60","A repair kit with adhesive, backing fabric, and a color-matched compound can hide small tears on cloth or vinyl. Functional, not invisible."),("Professional vinyl/cloth repair","$100\u2013$300","A trim shop patches and re-grains vinyl or re-weaves cloth for a near-invisible fix on a small tear or burn."),("Leather seat repair (single panel)","$200\u2013$500","A cut or tear in a leather panel can often be replaced by a trim shop without redoing the whole seat. Color-matching leather is the hard part."),("Full leather reupholster (one seat)","$600\u2013$1,500","When damage spans multiple panels, a full re-skin of the seat in matched leather is the clean fix. Luxury and Nappa leather run higher."),("Performance suede (Alcantara) repair","$500\u2013$1,200","Alcantara and similar suedes need specialist trimming and are easy to damage with the wrong cleaner. Re-paneling matches the grain poorly if faded.")],"insurance_q":"Does insurance cover a torn car seat?","insurance_a":"Usually not. Interior wear, tears, and burns are considered wear and tear or personal damage, not a covered peril. The exception is damage from a covered event (a break-in, a fire) or damage clearly caused in a rental or rideshare period \u2014 and even then, your proof is what wins it.","valet_q":"How do I prove a rideshare passenger or valet tore my seat?","valet_a":"Scan the interior \u2014 front and rear seats, door panels, and the cargo area \u2014 at the start and end of a rental or rideshare shift. A timestamped photo of an intact seat before the trip, then a photo of the tear after, is what rideshare platforms and rental companies accept as supporting evidence. Interior damage is the most-disputed category because it's invisible from outside; a cabin scan closes that gap.","related":[("Cost of Valet Damage Repair","/cost-of/valet-damage-repair"),("Rental Car Damage Claims","/learn/rental-car-damage-claims"),("Vehicle Handover Best Practices","/learn/vehicle-handover-best-practices")]},
    {"slug":"fuel-spill-clearcoat","category":"Exterior body","h1":"Fuel Spill Clear Coat Damage Repair Cost","meta_desc":"Fuel or solvent spilled on car paint costs $150 to compound and reseal, or $400\u2013$1,500+ to respray a damaged panel. How gasoline eats clear coat and how to document it.","lede":"Gasoline or solvent spilled on a fender eats through the clear coat in minutes, leaving a dull, stained patch. A light spill can be compounded and resealed for $150; a soak that's bubbled the paint means a $400\u2013$1,500 panel respray.","cards":[("Light spill, no etching (compound+seal)","$100\u2013$250","If caught quickly, a detailer can machine-polish the haze out and reapply a ceramic or sealant topcoat. No paint work."),("Moderate spill, dull patch","$200\u2013$450","Clear coat partially etched. Wet-sanding, polishing, and resealing can restore clarity if the base coat is intact."),("Severe spill, clear coat failure","$400\u2013$900","The clear coat has bubbled or lifted. The panel needs to be sanded to bare, re-primed, re-based, and re-cleared."),("Full panel respray (heavily soaked)","$700\u2013$1,500+","When fuel ran down the quarter panel and pooled at a body line, the damage often spans the whole panel and blending into the adjacent panel is needed.")],"insurance_q":"Is fuel-spill paint damage covered by insurance?","insurance_a":"Generally no \u2014 it's usually classed as a chemical or environmental exposure, not a collision or comprehensive peril. If the spill happened at a full-service gas station or in a valet/shop's care, their general liability is the target, but you'll need to prove the paint was intact beforehand and that the spill happened on their watch.","valet_q":"How do I prove fuel-spill damage happened at handover?","valet_a":"A pre-handover scan of the rear quarter panels \u2014 the most common place fuel dribbles during fill-up \u2014 is the baseline. A timestamped photo of clean, glossy paint at drop-off, then a photo of the dull, stained patch at pickup, attributes the damage. Spill damage is one of the easiest to win because the visual change is dramatic.","related":[("Cost of Valet Damage Repair","/cost-of/valet-damage-repair"),("How to Document Car Damage","/learn/how-to-document-car-damage"),("Insurance Claim Photo Tips","/learn/insurance-claim-photo-tips")]},
    {"slug":"towing-claw-damage","category":"Wheels & tires","h1":"Towing Damage Repair Cost: Hooks, Claws, and A-Frames","meta_desc":"Towing damage from hook-and-chain or wheel-lift contact costs $200 to fix a scuff to $3,000+ for a torn bumper or damaged suspension. How to document tow-truck damage for a claim.","lede":"Towing damage \u2014 a gouged bumper from a claw, a torn undertray from a hook, or curb-rashed wheels from a careless A-frame \u2014 runs $200 for a light scuff to $3,000+ for torn bodywork or damaged suspension. Tow companies fight these claims hard, so documentation is everything.","cards":[("Wheel-lift / A-frame scuffs","$100\u2013$400","Wheel and bumper scuffs from the tow rig's contact points. Often refinishable via PDR or a light repaint."),("Torn lower bumper / undertray","$400\u2013$1,200","Hooks and claws routinely tear the lower valance, fog-light housings, and plastic undertrays. Replacement plus paint."),("Damaged suspension / subframe","$1,000\u2013$3,000+","An improperly rigged tow can bend a control arm or damage the subframe. Requires a full alignment and possibly suspension replacement."),("Drivetrain damage (AWD/4WD)","$2,000\u2013$5,000+","Towing an AWD or 4WD vehicle on its drive wheels destroys the transfer case or center diff. A flatbed was required \u2014 if they didn't use one, they're liable.")],"insurance_q":"Who pays for towing damage?","insurance_a":"The tow company is liable for damage caused by their own rigging or driving, but they fight claims aggressively and their receipts disclaim liability for pre-existing damage. Your own collision or comprehensive coverage can pay (subject to your deductible) and then subrogate against the tow company. The deciding factor is always proof of the car's condition before they hooked it.","valet_q":"How do I document my car's condition before a tow?","valet_a":"Before the truck leaves with your car, scan every panel, wheel, and the underbody area you can reach. A timestamped, geotagged record of the car's condition at the moment of pickup is the only thing that defeats a tow company's 'pre-existing damage' defense. Towing claims are among the most contested; the pre-tow scan is non-negotiable.","related":[("Cost of Valet Damage Repair","/cost-of/valet-damage-repair"),("How to Dispute Valet Damage","/learn/how-to-dispute-valet-damage"),("Insurance Claim Photo Tips","/learn/insurance-claim-photo-tips")]},
]


def _faq_block(d):
    return json.dumps({"@context":"https://schema.org","@type":"FAQPage","mainEntity":[{"@type":"Question","name":d["insurance_q"],"acceptedAnswer":{"@type":"Answer","text":d["insurance_a"]}},{"@type":"Question","name":d["valet_q"],"acceptedAnswer":{"@type":"Answer","text":d["valet_a"]}}]})


def _siblings(d):
    """Return up to 3 sibling damage-type links in the same category (excluding self)."""
    out=[]
    for other in DAMAGE_TYPES:
        if other["slug"]==d["slug"] or other["category"]!=d["category"]:
            continue
        title=other["h1"].rstrip("?").split(":")[0].replace("Repair Cost","").replace("Cost","").strip()
        out.append((title, f'/cost-of/{other["slug"]}'))
        if len(out)>=3: break
    return out


def gen_cost_page(d):
    slug=d["slug"]; url=f"{BASE}/cost-of/{slug}"
    title=d["h1"].replace("?","")+" \u2014 CarShake"; desc=d["meta_desc"]
    cards_html="\n".join(f'<div class="cs-card"><h3 class="cs-h3" style="font-size:1rem;">{label}</h3><p style="font-size:1.3rem;font-weight:800;color:#0066cc;margin:6px 0">{price}</p><p class="cs-body-sm">{note}</p></div>' for label,price,note in d["cards"])
    related_html=" \u00b7 ".join(f'<a href="{href}">{label}</a>' for label,href in d["related"])
    sibs=_siblings(d)
    siblings_html=" \u00b7 ".join(f'<a href="{href}">{label}</a>' for label,href in sibs) if sibs else ""
    article_schema=json.dumps({"@context":"https://schema.org","@type":"Article","headline":d["h1"].rstrip("?"),"author":{"@type":"Organization","name":"CarShake"},"publisher":{"@type":"Organization","name":"CarShake","url":BASE},"datePublished":PUBDATE,"dateModified":PUBDATE,"mainEntityOfPage":url,"description":desc,"wordCount":750})
    breadcrumb_schema=json.dumps({"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":f"{BASE}/"},{"@type":"ListItem","position":2,"name":"Cost Guides","item":f"{BASE}/cost-of"},{"@type":"ListItem","position":3,"name":d["h1"].rstrip("?"),"item":url}]})
    faq_schema=_faq_block(d)
    return f"""<!doctype html><html lang="en"><head>
<meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0,viewport-fit=cover"/>
<title>{title}</title>
<meta name="description" content="{desc}">
<meta property="og:title" content="{title}">
<meta property="og:description" content="{desc}">
<meta name="twitter:title" content="{title}">
<meta name="twitter:description" content="{desc}">
<meta name="twitter:image" content="https://carshake.online/og-image.png">

<meta name="author" content="CarShake"/>
<meta property="og:type" content="article"/>
<meta property="og:url" content="{url}"/>
<meta property="og:image" content="https://carshake.online/og-image.png"/>
<meta property="og:image:width" content="1200"/><meta property="og:image:height" content="630"/>
<meta name="twitter:card" content="summary_large_image"/>
<link rel="canonical" href="{url}"/>
    <link rel="alternate" hreflang="en" href="{url}" />
    <link rel="alternate" hreflang="en-US" href="{url}" />
    <link rel="alternate" hreflang="x-default" href="{url}" />
<script type="application/ld+json">{article_schema}</script>
<script type="application/ld+json">{breadcrumb_schema}</script>
<script type="application/ld+json">{faq_schema}</script>

<link rel="stylesheet" crossorigin href="/assets/index-n3krrL_N.css">
<link rel="stylesheet" href="/design-system.css">
<link rel="modulepreload" crossorigin href="/assets/charts-DpChsq1R.js">
  <link rel="modulepreload" crossorigin href="/assets/markdown-EJqmjYtY.js">
  <link rel="modulepreload" crossorigin href="/assets/supabase-DMy4srAv.js">
  <script type="module" crossorigin src="/assets/index-ypvUJ8Vr.js"></script>
<!-- canonical-disambiguation --><script type="application/ld+json">{{"@context": "https://schema.org", "@type": "Organization", "name": "CarShake", "url": "https://carshake.online", "description": "CarShake is a free valet-damage-proof and vehicle-handover app that scans and time-stamps a car's condition before and after handover, giving drivers, valet operators, and rental fleets court-admissible proof to defeat false damage claims.", "disambiguatingDescription": "CarShake is a consumer-and-operator valet-damage-proof handover app (scan-before / scan-after + QR receipt) \u2014 not a B2B insurance damage-detection API."}}</script>
<link rel="stylesheet" href="/ux.css">
    <script src="/ux.js" defer></script>
  </head>
<body><div id="root"><div class="cs-page">
<header class="cs-header"><div class="cs-header-inner">
<a href="/" class="cs-logo">CarShake</a>
<nav class="cs-nav">
<a href="/free/valet-damage-claim-letter" class="cs-nav-link">Free Tools</a>
<a href="/pricing" class="cs-nav-link">Pricing</a>
<a href="/city" class="cs-nav-link">Cities</a>
<a href="/about" class="cs-nav-link">About</a>
<a href="/#demo" class="cs-nav-cta">Try Free</a>
</nav></div></header>
<main><div class="cs-container cs-section">
<nav class="cs-breadcrumb"><a href="/">Home</a> / <a href="/cost-of">Cost Guides</a> / <span>{d['h1'].split(':')[0] if ':' in d['h1'] else d['h1']}</span></nav>
<h1 class="cs-h1">{d['h1']}</h1>
<p class="cs-body" style="font-size:1.05rem;margin:var(--cs-space-2) 0 var(--cs-space-3)">{d['lede']}</p>
<div class="cs-stack cs-stack-md" style="margin:var(--cs-space-3) 0">
{cards_html}
</div>
<h3 class="cs-h3" style="font-size:1rem;margin-top:var(--cs-space-3)">{d['insurance_q']}</h3><p class="cs-body">{d['insurance_a']}</p>
<h3 class="cs-h3" style="font-size:1rem;margin-top:var(--cs-space-3)">{d['valet_q']}</h3><p class="cs-body">{d['valet_a']}</p>
<div class="cs-card cs-card-dark" style="margin:var(--cs-space-4) 0;text-align:center">
<p class="cs-h3" style="color:white">Don't pay for damage you didn't cause</p>
<p class="cs-body-sm" style="color:var(--cs-text-muted);max-width:520px;margin:0 auto var(--cs-space-3);line-height:1.5">CarShake documents your car's condition in 60 seconds before any handover \u2014 free, no download. Timestamped, QR-confirmed, court-ready.</p>
<a href="/#demo" class="cs-nav-cta" style="display:inline-block">Try CarShake Free \u2192</a>
</div><p class="cs-body" style="margin-top:var(--cs-space-3)"><strong>Related:</strong> {related_html}</p>{('<p class="cs-body-sm" style="margin-top:var(--cs-space-2)">Related damage-type costs: ' + siblings_html + '.</p>') if siblings_html else ''}</main></div></div></div>

<!-- BRUNSON TRUST BAR \u2014 idempotency:trust-bar-v1 -->
<section class="brunson-trust-bar" style="background:linear-gradient(135deg, #0f172a, #1e293b);color:#e8eaed;padding:40px 24px;margin:60px 0 0;border-top:3px solid #00d4aa;text-align:center;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif">
  <div style="max-width:900px;margin:0 auto">
    <div style="display:flex;flex-wrap:wrap;justify-content:center;gap:28px;margin-bottom:28px">

      <div><span style="font-size:1.6rem;font-weight:700;color:#00d4aa">60 sec</span><br><span style="font-size:.82rem;color:#94a3b8">Per Scan</span></div>
      <div><span style="font-size:1.6rem;font-weight:700;color:#00d4aa">8</span><br><span style="font-size:.82rem;color:#94a3b8">Angles Checked</span></div>

    </div>
    <p style="font-size:1.05rem;margin-bottom:24px;color:#cbd5e1">One dispute costs $500+. One scan prevents it. 3 free scans to prove it.</p>
    <a href="https://carshake.online/#demo" style="display:inline-block;background:linear-gradient(135deg,#00d4aa,#2deec0);color:#04130e;padding:14px 32px;border-radius:12px;font-weight:700;text-decoration:none;font-size:.95rem;box-shadow:0 8px 24px -10px rgba(0,212,170,.5)">Try CarShake Free \u2192</a>
    <p style="margin-top:18px;font-size:.78rem;color:#6b7178">\U0001f6e1\ufe0f Free to try. Scan before and after every handover for peace of mind.</p>
  </div>
</section>
<!-- /BRUNSON TRUST BAR -->

</body></html>"""


def gen_hub():
    by_cat={}
    existing=[("valet-damage-repair","Cost of Valet Damage Repair","From minor scrapes to panel replacement and paint matching.","Exterior body"),("valet-damage-claim-cost","Cost of a Valet Damage Claim","What a claim actually costs to file and win.","Exterior body"),("valet-insurance","Valet Insurance & Coverage","How insurance applies to valet damage and what it pays.","Insurance"),("rental-car-damage","Cost of Rental Car Damage","Rental company repair costs, loss-of-use, and admin fees.","Rental"),("rental-car-damage-cost","Rental Car Damage Cost Breakdown","What rental companies actually charge and how to fight it.","Rental")]
    for slug,title,desc,cat in existing: by_cat.setdefault(cat,[]).append((slug,title,desc))
    for d in DAMAGE_TYPES: by_cat.setdefault(d["category"],[]).append((d["slug"],d["h1"].rstrip("?").split(":")[0],d["meta_desc"]))
    cat_order=["Exterior body","Wheels & tires","Glass & lights","Interior","Rental","Insurance"]
    sections=[]
    for cat in cat_order:
        items=by_cat.get(cat)
        if not items: continue
        cards="\n".join(f'<div class="cs-card"><h3 class="cs-h3" style="font-size:1rem;margin:0 0 6px"><a href="/cost-of/{slug}" style="color:inherit;text-decoration:none">{title}</a></h3><p class="cs-body-sm">{desc[:140]}</p></div>' for slug,title,desc in items)
        sections.append(f'<h2 class="cs-h3" style="font-size:1.15rem;margin:var(--cs-space-4) 0 var(--cs-space-2)">{cat}</h2>\n<div class="cs-stack cs-stack-md">\n{cards}\n</div>')
    body="\n".join(sections)
    count=sum(len(v) for v in by_cat.values())
    desc=f"Real-world repair costs for every common type of car damage \u2014 door dings, curb rash, bumper scrapes, paint scratches, hail, and more. {count} cost guides from CarShake."
    return f"""<!doctype html><html lang="en"><head>
<meta charset="UTF-8"/><meta name="viewport" content="width=device-width,initial-scale=1.0,viewport-fit=cover"/>
<title>Vehicle Damage Repair Cost Guides | CarShake</title>
<meta name="description" content="{desc}">
<meta property="og:title" content="Vehicle Damage Repair Cost Guides | CarShake">
<meta property="og:description" content="{desc}">
<meta name="twitter:title" content="Vehicle Damage Repair Cost Guides | CarShake">
<meta name="twitter:description" content="{desc}">
<meta name="twitter:image" content="https://carshake.online/og-image.png">
<meta name="author" content="CarShake"/>
<meta property="og:type" content="website"/>
<meta property="og:url" content="https://carshake.online/cost-of"/>
<meta property="og:image" content="https://carshake.online/og-image.png"/>
<meta property="og:image:width" content="1200"/><meta property="og:image:height" content="630"/>
<meta name="twitter:card" content="summary_large_image"/>
<link rel="canonical" href="https://carshake.online/cost-of"/>
<link rel="alternate" hreflang="en" href="https://carshake.online/cost-of" />
<link rel="alternate" hreflang="en-US" href="https://carshake.online/cost-of" />
<link rel="alternate" hreflang="x-default" href="https://carshake.online/cost-of" />
<script type="application/ld+json">{{"@context":"https://schema.org","@type":"CollectionPage","name":"Vehicle Damage Repair Cost Guides","url":"https://carshake.online/cost-of","description":"{desc}","isPartOf":{{"@type":"WebSite","name":"CarShake","url":"https://carshake.online"}}}}</script>
<script type="application/ld+json">{{"@context":"https://schema.org","@type":"BreadcrumbList","itemListElement":[{{"@type":"ListItem","position":1,"name":"Home","item":"https://carshake.online/"}},{{"@type":"ListItem","position":2,"name":"Cost Guides","item":"https://carshake.online/cost-of"}}]}}</script>
<link rel="stylesheet" crossorigin href="/assets/index-n3krrL_N.css">
<link rel="stylesheet" href="/design-system.css">
<link rel="modulepreload" crossorigin href="/assets/charts-DpChsq1R.js">
  <link rel="modulepreload" crossorigin href="/assets/markdown-EJqmjYtY.js">
  <link rel="modulepreload" crossorigin href="/assets/supabase-DMy4srAv.js">
  <script type="module" crossorigin src="/assets/index-ypvUJ8Vr.js"></script>
<!-- canonical-disambiguation --><script type="application/ld+json">{{"@context": "https://schema.org", "@type": "Organization", "name": "CarShake", "url": "https://carshake.online", "description": "CarShake is a free valet-damage-proof and vehicle-handover app that scans and time-stamps a car's condition before and after handover, giving drivers, valet operators, and rental fleets court-admissible proof to defeat false damage claims.", "disambiguatingDescription": "CarShake is a consumer-and-operator valet-damage-proof handover app (scan-before / scan-after + QR receipt) \u2014 not a B2B insurance damage-detection API."}}</script>
<link rel="stylesheet" href="/ux.css">
    <script src="/ux.js" defer></script>
  </head>
<body><div id="root"><div class="cs-page">
<header class="cs-header"><div class="cs-header-inner">
<a href="/" class="cs-logo">CarShake</a>
<nav class="cs-nav">
<a href="/free/valet-damage-claim-letter" class="cs-nav-link">Free Tools</a>
<a href="/pricing" class="cs-nav-link">Pricing</a>
<a href="/city" class="cs-nav-link">Cities</a>
<a href="/about" class="cs-nav-link">About</a>
<a href="/#demo" class="cs-nav-cta">Try Free</a>
</nav></div></header>
<main><div class="cs-container cs-section">
<nav class="cs-breadcrumb"><a href="/">Home</a> / <span>Cost Guides</span></nav>
<h1 class="cs-h1">Vehicle Damage Repair Cost Guides</h1>
<p class="cs-body" style="font-size:1.05rem;margin:var(--cs-space-2) 0 var(--cs-space-3)">Real-world repair costs for every common type of car damage \u2014 what you'll actually pay, what insurance covers, and how to prove damage you didn't cause. Every guide is grounded in published market ranges, not guesses.</p>
{body}
</main></div></div></div>

<!-- BRUNSON TRUST BAR \u2014 idempotency:trust-bar-v1 -->
<section class="brunson-trust-bar" style="background:linear-gradient(135deg, #0f172a, #1e293b);color:#e8eaed;padding:40px 24px;margin:60px 0 0;border-top:3px solid #00d4aa;text-align:center;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif">
  <div style="max-width:900px;margin:0 auto">
    <div style="display:flex;flex-wrap:wrap;justify-content:center;gap:28px;margin-bottom:28px">
      <div><span style="font-size:1.6rem;font-weight:700;color:#00d4aa">60 sec</span><br><span style="font-size:.82rem;color:#94a3b8">Per Scan</span></div>
      <div><span style="font-size:1.6rem;font-weight:700;color:#00d4aa">8</span><br><span style="font-size:.82rem;color:#94a3b8">Angles Checked</span></div>
    </div>
    <p style="font-size:1.05rem;margin-bottom:24px;color:#cbd5e1">One dispute costs $500+. One scan prevents it. 3 free scans to prove it.</p>
    <a href="https://carshake.online/#demo" style="display:inline-block;background:linear-gradient(135deg,#00d4aa,#2deec0);color:#04130e;padding:14px 32px;border-radius:12px;font-weight:700;text-decoration:none;font-size:.95rem;box-shadow:0 8px 24px -10px rgba(0,212,170,.5)">Try CarShake Free \u2192</a>
    <p style="margin-top:18px;font-size:.78rem;color:#6b7178">\U0001f6e1\ufe0f Free to try. Scan before and after every handover for peace of mind.</p>
  </div>
</section>
<!-- /BRUNSON TRUST BAR -->

</body></html>"""


def sync_sitemap():
    sitemap=ROOT/"sitemap.xml"; text=sitemap.read_text()
    existing=set(re.findall(r"<loc>(https://carshake\.online/cost-of/[^<]+)</loc>",text))
    new_lines=[]
    for d in DAMAGE_TYPES:
        url=f"{BASE}/cost-of/{d['slug']}"
        if url not in existing: new_lines.append(f'  <url><loc>{url}</loc><lastmod>{TODAY}</lastmod><changefreq>weekly</changefreq><priority>0.7</priority></url>')
    if new_lines:
        text=text.replace("</urlset>","\n".join(new_lines)+"\n</urlset>"); sitemap.write_text(text)
        print(f"[sitemap] added {len(new_lines)} cost-of URLs")
    else: print("[sitemap] all cost-of URLs present")


def main():
    import sys; do_hub="--hub" in sys.argv; count=0
    for d in DAMAGE_TYPES:
        out_dir=ROOT/"cost-of"/d["slug"]; out_dir.mkdir(parents=True,exist_ok=True)
        (out_dir/"index.html").write_text(gen_cost_page(d)); count+=1
    print(f"[gen] wrote {count} cost-of pages"); sync_sitemap()
    if do_hub: (ROOT/"cost-of"/"index.html").write_text(gen_hub()); print("[hub] wrote cost-of/index.html")


if __name__=="__main__":
    main()
