// NLWeb endpoint for CarShake (Microsoft Copilot / Bing Chat)
// Auto-generated by growth engine

const content = [
  {
    "@type": "Question",
    "name": "How does CarShake prove vehicle damage?",
    "acceptedAnswer": "CarShake captures timestamped photos with GPS coordinates before and after valet parking, creating a verifiable evidence chain for damage disputes.",
    "url": "https://carshake.online/#faq"
  },
  {
    "@type": "Question",
    "name": "Is CarShake evidence legally valid?",
    "acceptedAnswer": "Yes, CarShake reports include cryptographic timestamps, GPS data, and unaltered photos that are admissible as evidence in small claims and insurance disputes.",
    "url": "https://carshake.online/#faq"
  },
  {
    "@type": "Question",
    "name": "Does CarShake work offline?",
    "acceptedAnswer": "Yes, CarShake works offline and syncs photos and reports when you reconnect. GPS and timestamps are captured locally.",
    "url": "https://carshake.online/#faq"
  }
];

export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
  
  if (req.method === 'OPTIONS') return res.status(200).end();
  
  const query = req.method === 'POST' 
    ? (req.body?.query || '').toLowerCase()
    : (req.query.query || '').toLowerCase();
  
  // Search FAQs
  const matches = query 
    ? content.filter(c => 
        c.name.toLowerCase().includes(query) || 
        c.acceptedAnswer.toLowerCase().includes(query)
      )
    : content;
  
  return res.json({
    '@context': 'https://schema.org',
    '@type': 'ItemList',
    'name': 'CarShake Knowledge Base',
    'description': 'Valet damage proof app. Document vehicle condition before and after parking with timestamped photos and GPS verification.',
    'numberOfItems': matches.length,
    'itemListElement': matches
  });
}
